{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "3e1ea323-910c-42ef-a4ec-4514ce401490",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "shape: (60, 9)\n",
      "Data type: order_id           int64\n",
      "order_date        object\n",
      "customer_name     object\n",
      "product           object\n",
      "category          object\n",
      "quantity         float64\n",
      "unit_price         int64\n",
      "region            object\n",
      "salesperson       object\n",
      "dtype: object\n",
      "Missing value per col:\n",
      "order_id         0\n",
      "order_date       0\n",
      "customer_name    3\n",
      "product          0\n",
      "category         0\n",
      "quantity         8\n",
      "unit_price       0\n",
      "region           0\n",
      "salesperson      0\n",
      "dtype: int64\n",
      "After handaling null value: (57, 9)\n",
      "After fixing the date: (54, 9)\n",
      "All checks passed!\n",
      "Final clean data shape: (54, 11)\n",
      "   order_id order_date customer_name   product     category  quantity  \\\n",
      "0      1001 2024-01-03   Riya Sharma    Laptop  Electronics       2.0   \n",
      "1      1002 2024-01-05    Amit Patel     Phone  Electronics       1.0   \n",
      "3      1004 2024-01-10    Priya Nair  Keyboard  Accessories       1.0   \n",
      "4      1005 2024-01-12   Rahul Desai    Laptop  Electronics       1.0   \n",
      "6      1007 2024-01-15   Karan Singh   Monitor  Electronics       2.0   \n",
      "\n",
      "   unit_price region salesperson   revenue order_month  \n",
      "0       55000   West        Amit  110000.0     2024-01  \n",
      "1       18000  North       Sneha   18000.0     2024-01  \n",
      "3        2500   East       Karan    2500.0     2024-01  \n",
      "4       55000   West        Amit   55000.0     2024-01  \n",
      "6       12000  South       Rahul   24000.0     2024-01  \n",
      "Connected to MySQL successfully!\n",
      "Data loaded successfully!\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "df=pd.read_csv(\"sales.csv\")\n",
    "print(\"shape:\",df.shape)\n",
    "\n",
    "print(\"Data type:\",df.dtypes)\n",
    "\n",
    "print(\"Missing value per col:\")\n",
    "print(df.isnull().sum())\n",
    "\n",
    "#Handling missing value..\n",
    "df=df.dropna(subset=[\"customer_name\"])\n",
    "\n",
    "df[\"quantity\"]=df[\"quantity\"].fillna(1)\n",
    "\n",
    "print(\"After handaling null value:\",df.shape)\n",
    "#Bad date fix\n",
    "df[\"order_date\"]=pd.to_datetime(df[\"order_date\"],errors=\"coerce\")\n",
    "df=df.dropna(subset=[\"order_date\"])\n",
    "\n",
    "print(\"After fixing the date:\",df.shape)\n",
    "df['revenue']=df[\"quantity\"]*df[\"unit_price\"]\n",
    "# Month column for reporting later\n",
    "df['order_month'] = df['order_date'].dt.to_period('M').astype(str)\n",
    "\n",
    "# Standardise text\n",
    "df['region']  = df['region'].str.strip().str.title()\n",
    "df['product'] = df['product'].str.strip().str.title()\n",
    "\n",
    "# Validate — make sure nothing slipped through\n",
    "assert df['order_id'].isnull().sum()   == 0, \"Nulls in order_id!\"\n",
    "assert df['revenue'].isnull().sum()    == 0, \"Nulls in revenue!\"\n",
    "assert df['order_date'].isnull().sum() == 0, \"Nulls in order_date!\"\n",
    "\n",
    "print(\"All checks passed!\")\n",
    "print(\"Final clean data shape:\", df.shape)\n",
    "print(df.head())\n",
    "\n",
    "from sqlalchemy import create_engine, text\n",
    "\n",
    "# Connect to MySQL\n",
    "engine = create_engine(\n",
    "    \"mysql+pymysql://root:@localhost:3306/sales_db\"\n",
    ")\n",
    "\n",
    "# Test connection\n",
    "with engine.connect() as conn:\n",
    "    conn.execute(text(\"SELECT 1\"))\n",
    "    print(\"Connected to MySQL successfully!\")\n",
    "\n",
    "    # Load clean data into MySQL\n",
    "df.to_sql(\n",
    "    name=\"sales\",\n",
    "    con=engine,\n",
    "    if_exists=\"replace\",\n",
    "    index=False\n",
    ")\n",
    "\n",
    "print(\"Data loaded successfully!\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "2e5777cb-f2fe-4a2a-aeb7-31040ef5146e",
   "metadata": {},
   "outputs": [],
   "source": [
    "import sys\n",
    "!{sys.executable} -m pip install pymysql"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "3f222411-24b7-4348-9727-c9eac287bd47",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:anaconda3]",
   "language": "python",
   "name": "conda-env-anaconda3-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
